const baseDeDatos = {
  "057695": {    carga: "MOTOCICLETA",    vehiculo: {      codigo: "812K3AC11CM057776",      tipo: "MOTO",      placa: "0",      carroceria: "Paseo",      color: "ROJO",      ejes: "2"    },    carnet: {      placa: "AA3M75J",      marca: "KEEWAY",      modelo: "HORSE KW-150",      anio: "2012"    },    pdfContrato: "CONTRATOS/57695 CARLOS Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57695 CARLOS Carnet.pdf"  },
  "057694": {    carga: "MOTOCICLETA",    vehiculo: {      codigo: "81J11D1D8RG003967",      tipo: "MOTO",      placa: "0",      carroceria: "0",      color: "GRIS",      ejes: "2"    },    carnet: {      placa: "AN3L94G",      marca: "TORO",      modelo: "TANK TR 180/180CC",      anio: "2024"    },    pdfContrato: "CONTRATOS/57694 KEVIN Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57694 KEVIN Carnet.pdf"  },
  "057697": {    carga: "AUTOMOVIL",    vehiculo: {      codigo: "8Z1MJ60038V342869",      tipo: "AUTOMOVIL",      placa: "0",      carroceria: "0",      color: "GRIS",      ejes: "5"    },    carnet: {      placa: "AA174IA",      marca: "CHEVROLET",      modelo: "SPARK / SPARK 1.0 T/M C ",      anio: "2008"    },    pdfContrato: "CONTRATOS/57697 MILZA Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57697 MILZA Carnet.pdf"  },
  "057698": {    carga: "REMOLQUE",    vehiculo: {      codigo: "MZ0039",      tipo: "REMOLQUE",      placa: "0",      carroceria: "0",      color: "AMARILLO",      ejes: "0"    },    carnet: {      placa: "A22BP8S",      marca: "FABRICACION NAC",      modelo: "SRB-56-3E",      anio: "1997"    },    pdfContrato: "CONTRATOS/57698 RICARDO Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57699RAINIERRT Carnet.pdf"  },
  "057699": {    carga: "MOTOCICLETA",    vehiculo: {      codigo: "8123AAK19RM296853",      tipo: "MOTO",      placa: "0",      carroceria: "PASEO",      color: "NEGRO",      ejes: "2"    },    carnet: {      placa: "AG9B38F",      marca: "KEEWAY",      modelo: "HORSE 150",      anio: "2024"    },    pdfContrato: "CONTRATOS/57699 RAINIERRT Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57698 RICARDO Carnet.pdf"  },
  "057705": {    carga: "CAMIONETA",    vehiculo: {      codigo: "8LDFTL52VY0001935",      tipo: "CAMIONETA",      placa: "0",      carroceria: "SPORT WAGON",      color: "GRIS",      ejes: "5"    },    carnet: {      placa: "AE204WD",      marca: "CHEVROLET",      modelo: "GRAND VITARA",      anio: "2000"    },    pdfContrato: "CONTRATOS/57705 OSCAR Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57705 OSCAR Carnet.pdf"  },
  "057706": {    carga: "AUTOMOVIL",    vehiculo: {      codigo: "JTNBK40K683034963",      tipo: "AUTOMOVIL",      placa: "2GR0456868",      carroceria: "SEDAN",      color: "GRIS",      ejes: "5"    },    carnet: {      placa: "AA341LG",      marca: "TOYOTA",      modelo: "CAMRY V6 / GSV40L-AETGKW",      anio: "2008"    },    pdfContrato: "CONTRATOS/57706 EFRAIN Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57706 EFRAIN Carnet.pdf"  },
  "057707": {    carga: "AUTOMOVIL",    vehiculo: {      codigo: "8Z1TJ5162AV306217",      tipo: "AUTOMOVIL",      placa: "0",      carroceria: "SEDAN",      color: "NEGRO",      ejes: "5"    },    carnet: {      placa: "AJ027UA",      marca: "CHEVROLET",      modelo: "AVEO / 1.6 4P T/A C/A",      anio: "2010"    },    pdfContrato: "CONTRATOS/57707 KELLEY Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57707 KELLEY Carnet.pdf"  },
  "057708": {    carga: "AUTOMOVIL",    vehiculo: {      codigo: "JTDJW923575039419",      tipo: "AUTOMOVIL",      placa: "0",      carroceria: "COUPE",      color: "PLATA",      ejes: "5"    },    carnet: {      placa: "FBR03F",      marca: "TOYOTA",      modelo: "YARIS 3 PUERTAS",      anio: "2007"    },    pdfContrato: "CONTRATOS/57708 LILIANA Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57708 LILIANA Carnet.pdf"  },
  "057709": {    carga: "AUTOMOVIL",    vehiculo: {      codigo: "H6EK14WV204575",      tipo: "AUTOMOVIL",      placa: "0",      carroceria: "SEDAN",      color: "BEIGE",      ejes: "5"    },    carnet: {      placa: "ABT48C",      marca: "HONDA",      modelo: "CIVIC EX 1.6 4A",      anio: "1998"    },    pdfContrato: "CONTRATOS/57709 JENIFER Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57709 JENIFER Carnet.pdf"  },
  "057710": {    carga: "RUSTICO",    vehiculo: {      codigo: "9FH11UJ9099025757",      tipo: "RUSTICO",      placa: "0",      carroceria: "SPORT WAGON",      color: "GRIS",      ejes: "5"    },    carnet: {      placa: "AB562AA",      marca: "TOYOTA",      modelo: "TOYOTA MERU/RZJ90L-GJMNKLA",      anio: "2009"    },    pdfContrato: "CONTRATOS/57710 HECTOR Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57710 HECTOR Carnet.pdf"  },
  "057714": {    carga: "AUTOMOVIL",    vehiculo: {      codigo: "ZFA146BS4M0203109",      tipo: "AUTOMOVIL",      placa: "0",      carroceria: "COUPE",      color: "PLATA",      ejes: "5"    },    carnet: {      placa: "XPJ737",      marca: "FIAT",      modelo: "UNO 1.6 R",      anio: "1991"    },    pdfContrato: "CONTRATOS/57714 FRANCISCO Venezolana_seguros.pdf",    pdfCarnet: "CONTRATOS/57714 FRANCISCO Carnet.pdf"  }
};
